import { useCallback, useEffect, useRef, useState } from "react";
// Generated loader entrypoint — registers the Stencil element (lazy dist output).
import { defineCustomElements } from "@functional-ui-poc/stencil/loader";
// Generated React wrapper (kept separate from hand-written public exports).
import { StencilFunctionalAction } from "@functional-ui-poc/stencil/react";
import type { FunctionalUIResult } from "@functional-ui-poc/stencil";
import type {
  FunctionalUIApi,
  FunctionalUIInput,
} from "@functional-ui-poc/shared-contract";
import { useApi } from "../../app/ApiProvider";
import { DebugPanel } from "../../components/DebugPanel";
import { TechPage } from "../../components/TechPage";
import { WorkflowSection } from "../../components/WorkflowSection";
import { useDebugLog } from "../../components/useDebugLog";
import { ProsCons } from "../../components/ProsCons";
import { TECH_NOTES } from "../../components/tech-notes";
import { DEMO_INPUT } from "../../demo-input";

// Register the custom element once (idempotent).
defineCustomElements();

const STENCIL_SUCCESS_EVENT = "functionalUiSuccess";

type StencilElement = HTMLElement & {
  input?: FunctionalUIInput;
  api?: FunctionalUIApi;
};

/**
 * Native section: create the Stencil-generated custom element directly, set its
 * typed props, and listen for its typed DOM event.
 */
function StencilNativeMount({
  api,
  onSuccess,
}: {
  api: FunctionalUIApi;
  onSuccess: (result: FunctionalUIResult) => void;
}) {
  const hostRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;

    const element = document.createElement(
      "functional-action-stencil"
    ) as StencilElement;
    element.api = api;
    element.input = DEMO_INPUT;

    const handler = (event: Event) => {
      onSuccess((event as CustomEvent<FunctionalUIResult>).detail);
    };
    element.addEventListener(STENCIL_SUCCESS_EVENT, handler);
    host.appendChild(element);

    return () => {
      element.removeEventListener(STENCIL_SUCCESS_EVENT, handler);
      element.remove();
    };
  }, [api, onSuccess]);

  return <div ref={hostRef} />;
}

export function StencilRoute() {
  const api = useApi();

  const native = useDebugLog();
  const react = useDebugLog();
  const [nativeResult, setNativeResult] = useState<FunctionalUIResult>();
  const [reactResult, setReactResult] = useState<FunctionalUIResult>();
  const [nativeKey, setNativeKey] = useState(0);
  const [reactKey, setReactKey] = useState(0);

  const { log: logNative, clear: clearNative } = native;
  const { log: logReact, clear: clearReact } = react;

  const onNativeSuccess = useCallback(
    (result: FunctionalUIResult) => {
      logNative(`functionalUiSuccess → ${result.selectedEntityId}`);
      setNativeResult(result);
    },
    [logNative]
  );

  const onReactSuccess = useCallback(
    (result: FunctionalUIResult) => {
      logReact(`onFunctionalUiSuccess → ${result.selectedEntityId}`);
      setReactResult(result);
    },
    [logReact]
  );

  const resetNative = () => {
    clearNative();
    setNativeResult(undefined);
    setNativeKey((key) => key + 1);
  };

  const resetReact = () => {
    clearReact();
    setReactResult(undefined);
    setReactKey((key) => key + 1);
  };

  return (
    <TechPage
      name="Stencil"
      summary={`Runs the "${DEMO_INPUT.actionId}" workflow via a Stencil web component.`}
    >
      <ProsCons {...TECH_NOTES.stencil} />

      <WorkflowSection
        mode="Native custom element"
        note="Registers via the generated /loader and renders <functional-action-stencil> directly."
      >
        <StencilNativeMount
          key={nativeKey}
          api={api}
          onSuccess={onNativeSuccess}
        />
        <DebugPanel
          entries={native.entries}
          result={nativeResult}
          onReset={resetNative}
        />
      </WorkflowSection>

      <WorkflowSection
        mode="React integration"
        note="Renders <StencilFunctionalAction>, the wrapper generated by @stencil/react-output-target."
      >
        <StencilFunctionalAction
          key={reactKey}
          input={DEMO_INPUT}
          api={api}
          onFunctionalUiSuccess={(event) =>
            onReactSuccess((event as CustomEvent<FunctionalUIResult>).detail)
          }
        />
        <DebugPanel
          entries={react.entries}
          result={reactResult}
          onReset={resetReact}
        />
      </WorkflowSection>
    </TechPage>
  );
}
