// Builds all three technology packages and generates `comparison-results.md`
// with objective metrics: bundle size (raw + gzip), CSS size, runtime
// dependency count, generated file count, build duration, type declarations,
// web-component support, and React wrapper strategy.
//
// A hand-maintained qualitative section (below the MANUAL-SECTION marker) is
// preserved across regenerations.

import { execSync } from "node:child_process";
import { readdirSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { build } from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MANUAL_MARKER = "<!-- MANUAL-SECTION -->";

/**
 * For each technology: how to build it, which built entry best represents "the
 * cost of using the component", and the qualitative facts the automated report
 * states as-is.
 */
const PACKAGES = [
  {
    key: "Lit",
    name: "@functional-ui-poc/lit",
    dir: "packages/lit-functional-ui",
    // `.` root entry statically re-exports the element + Lit runtime.
    bundleEntry: "dist/index.js",
    typesEntry: "dist/index.d.ts",
    distDirs: ["dist"],
    webComponent: "Yes — native custom element `functional-action-lit`",
    reactStrategy:
      "Hand-written thin wrapper (assigns props, bridges CustomEvent → `onSuccess`)",
  },
  {
    key: "Mithril",
    name: "@functional-ui-poc/mithril",
    dir: "packages/mithril-functional-ui",
    // `.` root entry statically pulls in `mountFunctionalAction` + Mithril.
    bundleEntry: "dist/index.js",
    typesEntry: "dist/index.d.ts",
    distDirs: ["dist"],
    webComponent: "No — framework-neutral `mountFunctionalAction()` into a host node",
    reactStrategy:
      "Hand-written React bridge over the mount API (update-in-place, remount on `api` change)",
  },
  {
    key: "Stencil",
    name: "@functional-ui-poc/stencil",
    dir: "packages/stencil-functional-ui",
    // Standalone custom-element output. The lazy `.` entry defers the component
    // via dynamic import, which a bundler would split — so the standalone
    // custom-element build is the fair "runtime cost" measure here.
    bundleEntry: "dist/components/functional-action-stencil.js",
    typesEntry: "dist/types/index.d.ts",
    distDirs: ["dist", "loader"],
    webComponent: "Yes — compiled custom element `functional-action-stencil`",
    reactStrategy:
      "Generated by `@stencil/react-output-target` (compiled to `dist/react`)",
  },
];

function kb(bytes) {
  return `${(bytes / 1024).toFixed(1)} kB`;
}

function countFilesRecursive(absDir) {
  if (!existsSync(absDir)) return 0;
  let count = 0;
  for (const entry of readdirSync(absDir, { withFileTypes: true })) {
    const full = path.join(absDir, entry.name);
    if (entry.isDirectory()) count += countFilesRecursive(full);
    else count += 1;
  }
  return count;
}

function sumCssBytes(absDir) {
  if (!existsSync(absDir)) return 0;
  let total = 0;
  for (const entry of readdirSync(absDir, { withFileTypes: true })) {
    const full = path.join(absDir, entry.name);
    if (entry.isDirectory()) total += sumCssBytes(full);
    else if (entry.name.endsWith(".css")) total += readFileSync(full).byteLength;
  }
  return total;
}

async function measureBundle(entryAbs) {
  const result = await build({
    entryPoints: [entryAbs],
    bundle: true,
    minify: true,
    format: "esm",
    platform: "browser",
    write: false,
    legalComments: "none",
    external: ["react", "react-dom", "react/jsx-runtime"],
  });
  const code = Buffer.from(result.outputFiles[0].contents);
  return { raw: code.byteLength, gzip: gzipSync(code).byteLength };
}

async function analyze(pkg) {
  const pkgDir = path.join(ROOT, pkg.dir);
  const manifest = JSON.parse(
    readFileSync(path.join(pkgDir, "package.json"), "utf8")
  );
  const runtimeDeps = Object.keys(manifest.dependencies ?? {});

  console.log(`\n▶ Building ${pkg.name} …`);
  const startedAt = Date.now();
  execSync(`pnpm --filter ${pkg.name} run build`, {
    cwd: ROOT,
    stdio: "ignore",
  });
  const buildMs = Date.now() - startedAt;

  const entryAbs = path.join(pkgDir, pkg.bundleEntry);
  const bundle = await measureBundle(entryAbs);

  const generatedFiles = pkg.distDirs.reduce(
    (sum, d) => sum + countFilesRecursive(path.join(pkgDir, d)),
    0
  );
  const cssBytes = pkg.distDirs.reduce(
    (sum, d) => sum + sumCssBytes(path.join(pkgDir, d)),
    0
  );
  const hasTypes = existsSync(path.join(pkgDir, pkg.typesEntry));

  return {
    ...pkg,
    runtimeDeps,
    buildMs,
    bundle,
    generatedFiles,
    cssBytes,
    hasTypes,
  };
}

function renderReport(rows, generatedAt) {
  const cell = (v) => `${v}`;

  const metricRows = [
    ["Bundled entry", (r) => `\`${r.bundleEntry}\``],
    ["Raw JS (minified, bundled)", (r) => kb(r.bundle.raw)],
    ["Gzipped JS", (r) => kb(r.bundle.gzip)],
    [
      "CSS size",
      (r) => (r.cssBytes > 0 ? kb(r.cssBytes) : "0 (styles inlined in JS)"),
    ],
    ["Runtime dependencies", (r) => `${r.runtimeDeps.length}`],
    ["Runtime dependency list", (r) => r.runtimeDeps.map((d) => `\`${d}\``).join(", ")],
    ["Generated files", (r) => `${r.generatedFiles}`],
    ["Build duration", (r) => `${(r.buildMs / 1000).toFixed(1)} s`],
    ["Type declarations", (r) => (r.hasTypes ? "Yes" : "No")],
    ["Web component", (r) => r.webComponent],
    ["React wrapper strategy", (r) => r.reactStrategy],
  ];

  const header = `| Metric | ${rows.map((r) => r.key).join(" | ")} |`;
  const sep = `| --- | ${rows.map(() => "---").join(" | ")} |`;
  const body = metricRows
    .map(
      ([label, fn]) =>
        `| ${label} | ${rows.map((r) => cell(fn(r))).join(" | ")} |`
    )
    .join("\n");

  const bundleNote = [
    "**How bundle size is measured:** each package's representative built entry is",
    "bundled and minified with esbuild (ESM, `react`/`react-dom` marked external),",
    "then measured raw and gzipped. This approximates what a consumer's bundler pulls",
    "in to render the component, framework runtime included. For Stencil the standalone",
    "custom-element output is measured; its lazy `.` entry defers the component via a",
    "dynamic import that a bundler would split into a separate chunk.",
  ].join(" ");

  return `# Functional UI POC — Comparison Results

_Automated metrics below are generated by \`pnpm compare\` (last run: ${generatedAt}). Do not edit above the manual-section marker; re-running \`pnpm compare\` overwrites it._

## Automated metrics

${header}
${sep}
${body}

${bundleNote}

${MANUAL_MARKER}

## Developer Experience (manually maintained)

_This section is preserved across \`pnpm compare\` runs. Filled in as part of ticket 07._
`;
}

/** Structured metrics the demo consumer imports to render the Home table. */
function buildData(rows, generatedAt) {
  return {
    generatedAt,
    technologies: rows.map((r) => ({
      key: r.key,
      bundledEntry: r.bundleEntry,
      rawJsBytes: r.bundle.raw,
      rawJs: kb(r.bundle.raw),
      gzipJsBytes: r.bundle.gzip,
      gzipJs: kb(r.bundle.gzip),
      cssBytes: r.cssBytes,
      css: r.cssBytes > 0 ? kb(r.cssBytes) : "0 (inlined in JS)",
      runtimeDeps: r.runtimeDeps.length,
      runtimeDepList: r.runtimeDeps,
      generatedFiles: r.generatedFiles,
      buildMs: r.buildMs,
      buildDuration: `${(r.buildMs / 1000).toFixed(1)} s`,
      typeDeclarations: r.hasTypes,
      webComponent: r.webComponent,
      reactStrategy: r.reactStrategy,
    })),
  };
}

async function main() {
  const rows = [];
  for (const pkg of PACKAGES) {
    rows.push(await analyze(pkg));
  }

  const generatedAt = new Date().toISOString();
  const outPath = path.join(ROOT, "comparison-results.md");
  let generated = renderReport(rows, generatedAt);

  // Preserve any existing manual section verbatim.
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, "utf8");
    const idx = existing.indexOf(MANUAL_MARKER);
    if (idx !== -1) {
      const preservedManual = existing.slice(idx);
      generated = generated.slice(0, generated.indexOf(MANUAL_MARKER)) + preservedManual;
    }
  }

  writeFileSync(outPath, generated);
  console.log(`\n✔ Wrote ${path.relative(ROOT, outPath)}`);

  // Also emit structured data the demo consumer renders on its Home route.
  const dataPath = path.join(
    ROOT,
    "apps/demo-consumer/src/comparison-data.json"
  );
  writeFileSync(dataPath, JSON.stringify(buildData(rows, generatedAt), null, 2) + "\n");
  console.log(`✔ Wrote ${path.relative(ROOT, dataPath)}`);
  console.table(
    rows.map((r) => ({
      Technology: r.key,
      "Raw JS": kb(r.bundle.raw),
      Gzip: kb(r.bundle.gzip),
      Deps: r.runtimeDeps.length,
      Files: r.generatedFiles,
      "Build (s)": (r.buildMs / 1000).toFixed(1),
    }))
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
