/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FunctionalUIApi, FunctionalUIInput, FunctionalUIResult } from "@functional-ui-poc/shared-contract";
export { FunctionalUIApi, FunctionalUIInput, FunctionalUIResult } from "@functional-ui-poc/shared-contract";
export namespace Components {
    /**
     * `<functional-action-stencil>` — typed props (`input`, `api`) and a typed event
     * (`functionalUiSuccess`), Shadow DOM, cleanup on disconnect. State lives in
     * `@State` fields; transitions live in `workflow.ts` and the view in
     * `workflow-view.tsx`, so the component stays a small declarative shell.
     */
    interface FunctionalActionStencil {
        "api"?: FunctionalUIApi;
        "input"?: FunctionalUIInput;
    }
}
export interface FunctionalActionStencilCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFunctionalActionStencilElement;
}
declare global {
    interface HTMLFunctionalActionStencilElementEventMap {
        "functionalUiSuccess": FunctionalUIResult;
    }
    /**
     * `<functional-action-stencil>` — typed props (`input`, `api`) and a typed event
     * (`functionalUiSuccess`), Shadow DOM, cleanup on disconnect. State lives in
     * `@State` fields; transitions live in `workflow.ts` and the view in
     * `workflow-view.tsx`, so the component stays a small declarative shell.
     */
    interface HTMLFunctionalActionStencilElement extends Components.FunctionalActionStencil, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFunctionalActionStencilElementEventMap>(type: K, listener: (this: HTMLFunctionalActionStencilElement, ev: FunctionalActionStencilCustomEvent<HTMLFunctionalActionStencilElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFunctionalActionStencilElementEventMap>(type: K, listener: (this: HTMLFunctionalActionStencilElement, ev: FunctionalActionStencilCustomEvent<HTMLFunctionalActionStencilElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFunctionalActionStencilElement: {
        prototype: HTMLFunctionalActionStencilElement;
        new (): HTMLFunctionalActionStencilElement;
    };
    interface HTMLElementTagNameMap {
        "functional-action-stencil": HTMLFunctionalActionStencilElement;
    }
}
declare namespace LocalJSX {
    /**
     * `<functional-action-stencil>` — typed props (`input`, `api`) and a typed event
     * (`functionalUiSuccess`), Shadow DOM, cleanup on disconnect. State lives in
     * `@State` fields; transitions live in `workflow.ts` and the view in
     * `workflow-view.tsx`, so the component stays a small declarative shell.
     */
    interface FunctionalActionStencil {
        "api"?: FunctionalUIApi;
        "input"?: FunctionalUIInput;
        "onFunctionalUiSuccess"?: (event: FunctionalActionStencilCustomEvent<FunctionalUIResult>) => void;
    }
    interface IntrinsicElements {
        "functional-action-stencil": FunctionalActionStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * `<functional-action-stencil>` — typed props (`input`, `api`) and a typed event
             * (`functionalUiSuccess`), Shadow DOM, cleanup on disconnect. State lives in
             * `@State` fields; transitions live in `workflow.ts` and the view in
             * `workflow-view.tsx`, so the component stays a small declarative shell.
             */
            "functional-action-stencil": LocalJSX.IntrinsicElements["functional-action-stencil"] & JSXBase.HTMLAttributes<HTMLFunctionalActionStencilElement>;
        }
    }
}
